on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create
        run: |
          ./gradlew wasmJsBrowserProductionWebpack
          cp -r noise/build/dist/wasmJs/productionExecutable public/noise
          cp -r starparallax/build/dist/wasmJs/productionExecutable public/starparallax

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public